name: usb
channels:
  - defaults
dependencies:
  - asttokens=2.0.5=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - bottleneck=1.3.7=py38h9128911_0
  - ca-certificates=2025.2.25=haa95532_0
  - colorama=0.4.6=py38haa95532_0
  - comm=0.2.1=py38haa95532_0
  - debugpy=1.6.7=py38hd77b12b_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - executing=0.8.3=pyhd3eb1b0_0
  - importlib_metadata=7.0.1=hd3eb1b0_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - ipykernel=6.29.5=py38haa95532_0
  - ipython=8.12.2=py38haa95532_0
  - jedi=0.19.1=py38haa95532_0
  - jupyter_client=8.6.0=py38haa95532_0
  - jupyter_core=5.7.2=py38haa95532_0
  - libffi=3.4.4=hd77b12b_1
  - libsodium=1.0.18=h62dcd97_0
  - matplotlib-inline=0.1.6=py38haa95532_0
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py38h2bbff1b_1
  - mkl_fft=1.3.8=py38h2bbff1b_0
  - mkl_random=1.2.4=py38h59b6b97_0
  - nest-asyncio=1.6.0=py38haa95532_0
  - numexpr=2.8.4=py38h7b80656_1
  - numpy-base=1.24.3=py38h8a87ada_1
  - openssl=3.0.16=h3f729d1_0
  - pandas=2.0.3=py38h4ed8f06_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=24.2=py38haa95532_0
  - prompt-toolkit=3.0.43=py38haa95532_0
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pygments=2.15.1=py38haa95532_1
  - python=3.8.20=h8205438_0
  - python-dateutil=2.9.0post0=py38haa95532_2
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - pytz=2024.1=py38haa95532_0
  - pywin32=305=py38h2bbff1b_0
  - pyzmq=25.1.2=py38hd77b12b_0
  - setuptools=75.1.0=py38haa95532_0
  - sqlite=3.45.3=h2bbff1b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tbb=2021.8.0=h59b6b97_0
  - tornado=6.4.1=py38h827c3e9_0
  - traitlets=5.14.3=py38haa95532_0
  - typing_extensions=4.11.0=py38haa95532_0
  - vc=14.42=haa95532_4
  - vs2015_runtime=14.42.34433=he0abc0d_4
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - wheel=0.44.0=py38haa95532_0
  - zeromq=4.3.5=hd77b12b_0
  - zipp=3.20.2=py38haa95532_0
  - pip:
      - absl-py==2.1.0
      - annotated-types==0.7.0
      - cachetools==5.5.2
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - click==8.1.8
      - contourpy==1.1.1
      - cycler==0.12.1
      - docker-pycreds==0.4.0
      - einops==0.8.1
      - et-xmlfile==2.0.0
      - eval-type-backport==0.2.2
      - filelock==3.16.1
      - fonttools==4.56.0
      - fsspec==2025.3.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - google-auth==2.38.0
      - google-auth-oauthlib==0.4.6
      - grpcio==1.70.0
      - huggingface-hub==0.29.3
      - idna==3.10
      - imageio==2.35.1
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - jinja2==3.1.6
      - joblib==1.4.2
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - markdown==3.7
      - markupsafe==2.1.5
      - matplotlib==3.7.5
      - mpmath==1.3.0
      - networkx==3.1
      - numpy==1.24.4
      - oauthlib==3.2.2
      - openpyxl==3.1.5
      - packaging==24.2
      - pillow==10.4.0
      - platformdirs==4.3.6
      - progress==1.6
      - protobuf==5.29.3
      - psutil==7.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pydicom==2.4.4
      - pyparsing==3.1.4
      - pywavelets==1.4.1
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - rsa==4.9
      - ruamel-yaml==0.18.10
      - ruamel-yaml-clib==0.2.8
      - safetensors==0.5.3
      - scikit-image==0.21.0
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - sentry-sdk==2.22.0
      - setproctitle==1.3.5
      - six==1.17.0
      - smmap==5.0.2
      - sympy==1.13.3
      - tensorboard==2.12.0
      - tensorboard-data-server==0.7.2
      - tensorboard-plugin-wit==1.8.1
      - threadpoolctl==3.5.0
      - tifffile==2023.7.10
      - timm==1.0.15
      - tokenizers==0.20.3
      - torch==2.4.1+cu118
      - torchaudio==2.4.1+cu118
      - torchvision==0.19.1+cu118
      - tqdm==4.67.1
      - transformers==4.46.3
      - typing-extensions==4.12.2
      - urllib3==2.2.3
      - wandb==0.19.8
      - werkzeug==3.0.6
prefix: D:\ProgramData\anaconda3\envs\usb
